### ISSUE TITLE
The 'Getting Started' section of README doesn't explain where to put the API key

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-ocean-sdk#222]
**Current Problem**
It explains that one needs to sign up for the Leap quantum cloud service, and then the next program from README fails with ```API token not defined```. There is no explanation of where should the API token be placed for scripts to find it.

**Comment by randomir** [comment]
There's a direct link to docs page about [solver access configuration](https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html) on Leap Dashboard page, under Solvers section:

![image](https://user-images.githubusercontent.com/447371/184901527-ba801d9f-3df8-445f-8d71-57343ed99ed1.png)

---

In the README, the second link from the one you mention (Leap signup), called [Getting Started with Ocean](https://docs.ocean.dwavesys.com/en/stable/getting_started.html) should (*) take you to the Getting Started page, with links to solver configuration as well.

![image](https://user-images.githubusercontent.com/447371/184902035-151fea64-f43f-4eb6-ac24-55140d8ce2aa.png)

(*) I say "should" because the link was broken until now (with a fix in #217 that we somehow forgot to merge).
